README.md, examples/sentry.yml, sentry.yml
New orb to add releases to Sentry. Published as `arrai/sentry@1.0.0`
=> feat: sentry release integration

README.md, examples/pypi.yml, pypi.yml
Add new orb to simplify publishing of packages to pypi and compatible repos.
Published as [arrai/pypi@1.0.0](https://circleci.com/developer/orbs/orb/arrai/pypi?version=1.0.0)
=> feat: pypi integration

sentry.yml
- added `deploy_release` job that allows adding reploys to releases on sentry.
- removed redundancies in the `create_release` job.
- published as [arrai/sentry@2.0.0](https://circleci.com/developer/orbs/orb/arrai/sentry?version=2.0.0)
=> feat: add deploy job

github.yml
Files persisted to the workspace can now be uploaded as part of the release on github.
Published as [arrai/github@1.1.0](https://circleci.com/developer/orbs/orb/arrai/github?version=1.1.0)
=> feat: allow files to be uploaded as part release creation

eslint.yml, flake8.yml, prettier.yml
Because of how these scripts are compiled, using pipeline variables doesn't work as expected. Use a boolean to indicated whether or not you want badges. Defaults to true to preserve historical behaviour.
Published as:
- [arrai/prettier@5.0.0](https://circleci.com/developer/orbs/orb/arrai/prettier?version=5.0.0)
- [arrai/flake8@13.0.0](https://circleci.com/developer/orbs/orb/arrai/flake8?version=13.0.0)
- [arrai/eslint@7.0.0](https://circleci.com/developer/orbs/orb/arrai/eslint?version=7.0.0)
=> fix: deal with pipeline parameters not working as expected

flake8.yml
Published as [arrai/flake8@13.1.0](https://circleci.com/developer/orbs/orb/arrai/flake8?version=13.1.0)
=> fix: default to python 3.8

npm.yml
Published as [arrai/npm@2.6.0](https://circleci.com/developer/orbs/orb/arrai/npm?version=2.6.0)
- make `report_to` parameter optional and skip audit email if unset
- bumped node minor releases where applicable
=> make npm audit results email optional

badass.yml
Since this orb only supports pipenv now, the Pipfile.lock should provide the required functionality.
=> chore: remove pip freeze file generation & upload

orbs/utils.yml
rsync uploads and shields.io badge generation should now work with job names that contain spaces. The circleci documentation implies that this is not supported, however, it does seem to work... I can't recommend actually doing this as there are probably tons of edge cases where this breaks. Nonetheless, we've added some compatibility here. This has been published as arrai/utils@1.12.0.
=> feat: allow spaces in job names

orbs/prettier.yml
- use `npm ci` to install prettier if no version is supplied
- no longer update to the latest npm version since that might be too new for the package.lock
- bump to node 16 as the default executor as 14 is pending EOL
- bump utils orb
Published as `arrai/prettier@dev:70` for testing
=> fix: address issue #70 by using npm ci when no prettier version is given

orbs/badass.yml
Defaulting to `medium` had the unintended consequence of overriding the `resource_class` specified on the passed-in executor as the job level `resource_class` is of higher priority. Unfortunately there is not a way to have a truly optional parameter; it's either required or must have a default.
=> fix: make resource_class mandatory

orbs/eslint.yml, orbs/npm.yml, orbs/prettier.yml
Published as `arrai/eslint@7.5.0`, `arrai/npm@2.7.0`, and `arrai/prettier@5.3.0`
=> chore: bump to latest nodejs releases

orbs/eslint.yml, orbs/npm.yml, orbs/prettier.yml
- bump defaults to node 18; node 16 is EOL September 11th
- bump minimum version of node 18 as npm 10 doesn't support < 18.17
=> chore: bump node versions

orbs/badass.yml
We no longer need to use the `--python` flag on `pipenv install` command, since the venv has been created.
=> fix: Use the correct Python for `pipenv clean`.

orbs/pypi.yml
The key used to restore the cache was unconfigurable and based on the OS release. In cases where a custom executor is used as part of the build process, that executor is then required to be used as part of the publish process, which doesn't make much sense; the publisher only needs to upload an already built wheel to the pypi server.
- allow for a cache key to be specified via the `cache_key` parameter; default to the current implementation
- don't check out the source tree from the repo; it's not required here.
Published as `arrai/pypi@3.1.0`
=> feat: allow configurable cache key

README.md, examples/pypi.yml
As of version 2+ of the pypi orb, it's expected that the build files are stored to cache rather than be persisted to the workspace. Update the README and example to reflect that.
=> docs: update pypi publish information & example

orbs/badass.yml, orbs/eslint.yml, orbs/flake8.yml, orbs/npm.yml, orbs/prettier.yml, orbs/safety.yml
Set jobs that upload to our servers to use circle's fixed ip ranges.
Published as:
- `arrai/badass@17.1.0`
- `arrai/prettier@5.6.0`
- `arrai/flake8@17.1.0`
- `arrai/eslint@7.7.0`
- `arrai/safety@2.1.0`
- `arrai/npm@2.10.0`
=> feat: use circleci's private IP ranges

orbs/badass.yml, orbs/eslint.yml, orbs/flake8.yml, orbs/npm.yml, orbs/prettier.yml, orbs/pytest.yml, orbs/safety.yml
As mentioned in the [discussion here](https://discuss.circleci.com/t/ip-ranges-open-preview/40864), using `circleci_ip_ranges` in a configurable way by passing in the value via an exposed parameter is currently broken. Since this has been an open issue for a long time, I'm not holding my breath that this will get fixed any time soon.
The workaround is rather annoying; create separately named jobs that can be called as appropriate. In order for this not to lead to massive amounts of code duplication, I'm reusing the parameters and steps in those jobs via aliases & anchors.
This means many jobs now have been duplicated with a `fixed_ip` suffix to indicate those run in the fixed network range.
`arrai/eslint@7.8.0`
- `eslint`
- `eslint_fixed_ip`
`arrai/prettier@5.7.0`
- `code_style`
- …
=> feat: allow optional use of fixed ip ranges

orbs/badass.yml
We dropped support for tests using plain requirements.txt files with `arrai/badass@14.0.0`, however, we have several projects that haven't been switched to use pipenv. Since one can't release patch/minor updates for older major version releases on CircleCI, and I wanted to make use of fixed IP ranges, I've ported a variant of the old functionality to the current release.
This adds a new `badass_venv_test_pre_spread`. `badass_test_pre_spread` remains as the pipenv variant. `badass_test_spread` and `badass_test_combine` have been updated with a `use_pipenv` boolean that defaults to `true`. If set to `false`, pip is used instead of pipenv.
This has been published as `arrai/badass@17.2.0` as this is intended as a non-breaking change for projects already on v17.
=> feat: allow venv-based tests again

orbs/eslint.yml, orbs/npm.yml, orbs/prettier.yml, package-lock.json
- `add_ssh_config` would run even when badges weren't being requested, this causes problems when the job is run without fixed IP addresses.
- bumped node images to the latest releases, published as:
- `arrai/npm@2.12.2`
- `arrai/prettier@5.8.1`
- `arrai/eslint@7.9.1`
=> fix: add ssh keys only when needed when running npm audit job

orbs/npm.yml
Allow the version number of npm to be specified. Default to `latest` to preserve the behaviour of previous releases. Published as `arrai/npm@2.12.3`
=> feat: allow the installed npm version to be specified

README.md, orbs/badass.yml, orbs/eslint.yml, orbs/flake8.yml, orbs/npm.yml, orbs/prettier.yml, orbs/pytest.yml, orbs/safety.yml, orbs/utils.yml
- add dynamic orb version badges so that the latest releases can be more easily identified
- reorder the docs into alphabetical order
- bump to the latest utils orb to take advantage of fixes to `add_ssh_config`
- remove the `add_maxmind_config` steps from the `badass` orb; it's no longer required. The docker images have been updated with a version of `geoipupdate` that can take in configuration options via environment variables. These are set via the `arrai-maxmind` context.
- switched to only having `current` and `lts` node executors in the orbs and default to `lts`. Having fixed version numbers in the orbs doesn't make much sense;  if a workflow needs a specific version, it should be set via an overriding executor.
- dropped python 3.6 and added 3.11 and 3.12 to the available python …
=> chore: fixes and optimizations

orbs/badass.yml, orbs/eslint.yml, orbs/flake8.yml, orbs/npm.yml, orbs/prettier.yml, orbs/pytest.yml, orbs/safety.yml
The `arrai/utils@1.16.0` orb was published from an incorrect branch. This was corrected as `arrai/utils@1.16.1`, however, that requires  bumping the version in all the dependent orbs. These have been released as the following patch revisions:
- `arrai/badass@17.5.1`
- `arrai/eslint@7.10.1`
- `arrai/flake8@19.0.1`
- `arrai/npm@3.0.1`
- `arrai/prettier@5.9.1`
- `arrai/pytest@8.0.1`
- `arrai/safety@3.0.1`
=> chore: bump utils orb to the latest patch level

orbs/flake8.yml
Published as `arrai/flake8@20.0.0`.
=> feat: use the python version in cache-key generation

orbs/pytest.yml
Check if we already have `pipenv` before we waste time trying to install it.
Published as `arrai/pytest@8.1.2`
=> chore: optimize pipenv install

orbs/utils.yml
The `install_rsync` function wasn't sensitive to the `when:` parameter. Since the default for this parameter is `on_success`, rsync would fail to get installed if any previous step had set a failure condition. This could result in error badges not being uploaded.
Fix published as `arrai/utils@1.16.2`. We'll bump all the orbs with this version in a subsequent PR.
=> fix: make rsync_install respect the when parameter

orbs/badass.yml, orbs/eslint.yml, orbs/flake8.yml, orbs/npm.yml, orbs/prettier.yml, orbs/pytest.yml, orbs/safety.yml, orbs/utils.yml
Bumped the utils orb to the latest fixed release in all the other orbs. This resulted in the following releases:
`arrai/badass@17.5.2`
`arrai/eslint@7.10.2`
`arrai/flake8@20.0.1`
`arrai/npm@3.0.2`
`arrai/prettier@5.9.2`
`arrai/pytest@8.1.3`
`arrai/safety@3.0.2`
=> chore: bump utils orb to latest release

orbs/flake8.yml, orbs/pytest.yml, orbs/safety.yml
We weren't cleaning up packages that were no longer listed in the lock file, which could lead to problems when restoring from cache.
Released as:
`arrai/eslint@8.0.1`
`arrai/pytest@8.1.5`
`arrai/safety@3.0.4`
=> fix: run pipenv clean to remove extraneous packages

orbs/utils.yml, package-lock.json
We've been duplicating this in a lot of ci configs.
Published as `arrai/utils@1.17.0`
=> feat: add command to install dockerize

orbs/badass.yml, orbs/eslint.yml, orbs/flake8.yml, orbs/npm.yml, orbs/prettier.yml, orbs/pytest.yml, orbs/safety.yml, orbs/utils.yml
- Spit out the `rsync` command line as a convenience.
- Remove the re-setting of the `LANG` environment variable. This does nothing useful at the moment; no subsequent commands run in the step and environment variables don't carry over to the next step.
The version of the utils orb was bumped to 1.18.0. The dependencies in the other orbs were updated and released as the following:
- `arrai/badass@17.6.0`
- `arrai/eslint@8.1.0`
- `arrai/flake8@20.1.0`
- `arrai/npm@3.1.0`
- `arrai/prettier@5.10.0`
- `arrai/pytest@8.2.0`
- `arrai/safety@3.1.0`
=> feat: echo rsync command line

orbs/github.yml
- sha1 commit hashes aren't valid as targets for releases, only tags are allowed.
- switch back to using `set -- $@` to append the selected command line arguments as this properly lets expansion like `~` work.
Published as a new major, `arrai/github@5.0.0`, as it changes a parameter key.
=> chore: github release fixes

orbs/utils.yml
Not sure about the command naming. Thoughts?
The logic is as follows:
- If there is no changelog; return success. Maybe it was deleted.
- If there is only one tag, return success since there can be no changes.
- If the `git diff` between the current and last tag doesn't contain the changelog, error.
Currently just published as `arrai/utils@dev:101`
=> feat: add command to check if changelog was updated between tags

orbs/safety.yml
Pin to a version of `pipenv` that bundles safety 2.x to preserve compatability with the `pipenv --check` command.
Published as `arrai/safety@4.1.0`
=> fix: pin pipenv to a release that bundles safety 2.x

orbs/badass.yml
This drops support for using `pipenv` and `pip`. Older projects can continue to use the previous orb until they've been transitioned.
This orb has been published as `arrai/badass@18.0.0`.
=> Switch to uv as the package manager for setting up badass tests

orbs/flake8.yml
Add jobs that can be called by projects using `uv` as the package manager to run the `flake8` linter using `pre-commit` hooks, since they don't include `flake8` in any installable package grou.
Published as `arrai/flake8@20.2.0`.
=> allow projects using 'uv' to run the flake8 linter via 'pre-commit' hooks instead.

orbs/utils.yml
Add the ability to configure the badge parameters via a JSON document. The requirement for supporting this arose from the WIP to combine linting into a single job or workflow. Typically we set the parameters for the badge based on the pass/fail status of the job, but in this case, that doesn't work since the pass/fail is global on the job, but we want to generate badges based on the fail/pass of an individual step.
To simplify matters, calling the command with no parameters, generates a passing badge. This does not impact any existing use of this command.
This has been published as `arrai/utils@1.20.0` and has been tested in the https://github.com/arrai-innovations/circleci-test repo.
=> feat: allow badges to be configured via config files

orbs/badass.yml
Since `uv run` always syncs, we we'd need to enable private network ranges to run the tests, which would significantly raise the costs for these long tests. Instead, we can activate the virtual environment and run `coverage` directly.
Published as `arrai/badass@18.1.0`
=> fix: run "coverage" directly rather than via "uv run"

README.md, orbs/pip-audit.yml
Published as `arrai/pip-audit@1.0.0`
This serves as a replacement for the `arrai/safety` orb. Safety's licensing changes make it unsuitable for running in CI/CD pipelines. As `pipenv check` uses `safety` behind the scenes, newer releases suffer from the same problem. `uv` does not currently have a native audit system.
This  supports three environment types: plain `pip` via a `requirements.txt`, `pipenv`, and `uv`.
=> add pip-audit orb

orbs/pytest.yml
Support both `uv` and `pipenv` as python environment managers. Default to `pipenv` to remain compatability with the older release. That said, this is somewhat of a breaking change since the cache key busting parameter has been renamed. 
Published as `arrai/pytest@9.0.0`
=> feat: support uv as a python environment manager in pytest
